Add way to global handle Exceptions in event()
fomkin/korolev pull request #417
Opened 2022-01-18 16:41 UTC by greenhost87

2022-01-21 09:05 UTC, fomkin reviewed
It's will be good to add recovery to render.

2022-01-21 09:05 UTC, fomkin commented on modules/korolev/src/main/scala/korolev/server/KorolevServiceConfig.scala
> +  def eventRecovery: Context.Access[F, _, _] => PartialFunction[Throwable, F[Unit]] = { _ =>
How to define it? Extend KorolevServiceConfig?

2022-01-21 09:05 UTC, fomkin commented on modules/korolev/src/test/scala/korolev/Issue14Spec.scala
> +      eventRecovery = ???
PartialFunction.empty

2022-01-22 08:04 UTC, greenhost87 commented on modules/korolev/src/main/scala/korolev/server/KorolevServiceConfig.scala
> +  def eventRecovery: Context.Access[F, _, _] => PartialFunction[Throwable, F[Unit]] = { _ =>
yes

2022-02-02 10:31 UTC, greenhost87 commented on modules/korolev/src/main/scala/korolev/server/KorolevServiceConfig.scala
> +  def eventRecovery: Context.Access[F, _, _] => PartialFunction[Throwable, F[Unit]] = { _ =>
Change to parameter, no extend needed

2022-02-12 06:40 UTC, fomkin requested changes

2022-02-12 06:40 UTC, fomkin commented on modules/korolev/src/main/scala/korolev/internal/ComponentInstance.scala
> +          case e: MatchError =>
Why not to move this case to catch section below?

2022-02-12 06:40 UTC, fomkin commented on modules/korolev/src/main/scala/korolev/internal/ComponentInstance.scala
> -import korolev._
Did you try to compile this with 2.12? Does it work?

2022-02-12 06:40 UTC, fomkin commented on modules/korolev/src/main/scala/korolev/server/KorolevServiceConfig.scala
> +  actionRecovery: Context.Access[F, _, _] => PartialFunction[Throwable, F[Unit]] = { _: Context.Access[F, _, _] =>
stateLoader, document, reproter. Maybe recover or recovery?

2022-02-12 06:40 UTC, fomkin commented on modules/korolev/src/main/scala/korolev/internal/ComponentInstance.scala
> +        actionRecovery(browserAccess)(ex)
This will not work with Monix/IO/ZIO. You should invoke `runAsync`.

2022-03-22 08:14 UTC, greenhost87 commented on modules/korolev/src/main/scala/korolev/server/KorolevServiceConfig.scala
> +  actionRecovery: Context.Access[F, _, _] => PartialFunction[Throwable, F[Unit]] = { _: Context.Access[F, _, _] =>
changed to recovery

2022-04-09 08:11 UTC, merged